name: qr_code_scanner_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  qr_code_scanner: ^1.0.1  # Update this to the latest version if available
  geolocator: ^9.0.2
  path_provider: ^2.0.11
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0  # For local storage

flutter:
  uses-material-design: true